improve debuggability of json ser/de errors (#1119)
# Description

JSON serde errors are very hard to debug because they are usually
displayed with the following vague error messages:

```
Error: Invalid JSON in log record: EOF while parsing a value at line 1 column 1                                                                                                              
                                                                                                                                                                                             
Caused by:                                                                                                                                                                                   
    EOF while parsing a value at line 1 column 1  
```

This PR separates JSON ser/de errors by different scenarios as well as
adding more context to each error whenever applicable.