Handle the possibility that a filesystem is None when writing in Python
I don't understand how this wasn't failing before since filesystem is Optional
in the type, error in Actions:

    mypy
    deltalake/writer.py:223: error: Item "None" of "Optional[Any]" has no attribute "get_file_info"  [union-attr]
    Found 1 error in 1 file (checked 7 source files)