fix: fall back to older converted_types when using parquet for stats
This was an interesting :bug: to smush!

The latest delta-kernel-rs introduced a regression in one of our tests

         thread 'operations::convert_to_delta::tests::test_convert_to_delta' (7352) panicked at crates/core/src/operations/convert_to_delta.rs:671:9:
        assertion failed: `(left == right)`

        Diff < left / right > :
         [
        <    Null(
        <        Primitive(
        <            Date,
        <        ),
        >    Date(
        >        18628,
             ),
             Integer(
                 1,
             ),
         ]

The `date` column of
`crates/test/tests/data/delta-0.8.0-date/part-00000-d22c627d-9655-4153-9527-f8995620fa42-c000.snappy.parquet`
which is used by this test is _old_ and uses an older Apache Parquet
format which uses the `converted_type` field rather than a logical type.

        ############ Column(date) ############
        name: date
        path: date
        max_definition_level: 1
        max_repetition_level: 0
        physical_type: INT32
        logical_type: Date
        converted_type (legacy): DATE
        compression: SNAPPY (space_saved: -3%)

In the statistics generation code which relies on the parquet footer
metadata, this was causing the logical/converted type to be missed and
instead this was getting interpreted as an Iht32.

The kernel change was introduced in delta-io/delta-kernel-rs@c96deafd
and modified the behavior of the default engine's JSON parsing.
Previouly this test probably was only succeeding because the value used
for statistics generation wasn't as strict on a "Date" type as it now
is. This meant that the "int32" version of the date was _fine_ as far as
the stats were concerned, but that is no longer the case.

I will not be surprised if this strictness causes more issues in
real-world parquet files with statistics parsing.

Signed-off-by: R Tyler Croy <rtyler@brokenco.de>