Introduce a failing test for #1286
This test currently fails because the RecordBatchWriter doesn't like the
difference between Timestamps:

---- writer::record_batch::tests::test_write_batch_with_timestamps stdout ----
thread 'writer::record_batch::tests::test_write_batch_with_timestamps' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("column types must match schema types, expected Timestamp(Microsecond, None) but found Timestamp(Nanosecond, None) at column index 1")', rust/src/writer/record_batch.rs:507:101
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace